Python was originally a general purpose language, But over the years, it has gained attention for data analysis and machine learning.  In thsi notebook we will learn about the basics of Python for data analysis. we will learn about important libraries for data analysis etc.  

### Why learn Python for data analysis?
In the recent past, Python has gained lot of attention for data analysis and machine learning domain. Here are some reasons for the popularity of python. Main reason for learning python is simplicity. 

- Simplicity - When you first start with programming and coding, you don’t want to start with a programming language which has tough syntax and weird rules.

Python is both readable and simple. It also easier to setup, you don’t need to deal with any classpath problems like Java or compiler issues like C++.

- Open source - free to install

- Big online community

- Easy to learn

- Libraries and Frameworks - Python has numerous libraries for different needs. Django and Flask are two of the most popular for web development and NumPy and SciPy and Pandas are for Data Science.

In fact, Python has one of the best collection of machine learning and data science libraries like TensorFlow, Scikit-Learn, Keras, Pandas and many more.

- Multipurpose - common language for web development and data science. You can create your web applications using Django and Flask, Can do Data Analysis using NumPy, Scipy, Scikit-Learn, and NLTK.

= What makes Python a preferred language for Data Science and Machine Learning. There are powerful APIs and library available for AI, Data Science, and Machine learninge.e.g., Numpy, Pandas, ScikitLearn, MatplotLib, 



#### How to install Python
ou can download Python directly from its project site and install individual components and libraries you want

https://www.python.org/download

Alternately, you can download and install a package, which comes with pre-installed libraries.
I would recommend downloading Anaconda.
https://www.continuum.io/downloads



In [1]:
## Print the version

import sys
print(sys.version)

3.7.7 (default, Mar 23 2020, 17:31:31) 
[Clang 4.0.1 (tags/RELEASE_401/final)]


#### Python libraries and Data Structures

- Lists
- Tuples
- Dictionary

It is assumed that you are familair with basic Python like loops, iterators, functions etc. 

#### Libraries

The first step to learn Python is by getting acquainted with useful libraries. we nedd to learn how to import libraries into our environment. There are several ways of doing.   

In [2]:
import math as m



In [ ]:
from math import *

In the first manner, we have defined an alias m to library math. We can now use various functions from math library (e.g. square root) by referencing it using the alias m.sqrt().

In the second manner, we have imported the entire name space in math i.e. you can directly use sqrt() without referring to math.

Following are a list of libraries, oned needs for scientific computations and data analysis


##### numpy :   
stands for Numercial Python. 
##### scipy
stand for Scientific Python. Scipy is built on numpy. 
##### pandas
for structured data operations and manipulations
##### matplotlib
fro plotting vast variety of graphs.
##### sklearn
for machien learning
#### statsmodels
for statistical models
##### seaborn
fro data visualization. It si based on matplotlib . 
##### bokeh
##### scrapy
##### sympy
##### requests


There are some more. look for it.




# Numpy and Scipy

Numerical Python (NumPy) is an open source Python library for scientific computing.  The NumPy (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numeric data. It is a foundational package on which many of the data science packages are built. pandas builds upon functionality provided by Numpy. The pandas library relies heavily on the NumPy array for the implementation of the pandas Series and DataFrame objects, and shares many of its fetaures such as being able to slice elements and perform vectorized operations. It is therefore useful to spend time going over NumPy arrays before diving into pandas. 


For any scientific project, NumPy is the tool to know. It has been built to work with the N-dimensional array, linear algebra, random number, Fourier transform, etc. It can be integrated to C/C++ and Fortran.
The key features of NumPy are:

* ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient. There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).

* Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.

* Vectorization: enables numeric operations on ndarrays.

* Input/Output: simplifies reading and writing of data from/to file.


The SciPy (Scientific Python) package extends the functionality of NumPy with a substantial collection of useful algorithms, like minimization, Fourier transformation, regression, and other applied mathematical techniques.

#### Why use NumPy?
NumPy is memory efficient, i.e., it can handle lage amount of data more accessible than any other library.  Moreover, Numpy is very convenient to work with, especially for matrix multiplication and reshaping as mentioned earlier. It is fast. Many advanced Python libraries, such as Scikit-Learn, Scipy, and Keras, make extensive use of the NumPy library. Therefore, if you plan to pursue a career in data science or machine learning, NumPy is a very good tool to master.


### Installation

If you have aintsalled Anaconda, then you should be ready to go. If not, then you will have to install add-ons manually after installing Python, in the order of Numpy and the Scipy. You can use pip installer. Excute the follwing command toinstall:

 pip install numpy

Otherwise, if you are running Python via the Anaconda distribution, you can execute the following command instead:

conda install numpy

### Importing the Numpy module
There are several ways to import Numpy. The standard approach is to use a simple import setatement: 

In [3]:
#import numpy

However, for large amounts of calls to NumPy functions, it can become tedious to write numpy.X over and over again. Instead, it is common to import under the briefer name np:

In [2]:
import numpy as np

Above code renames the Numpy namespace to np. This permits us to prefix Numpy function, methods, and attributes with " np " instead of typing " numpy."
This statement will allow us to access NumPy objects using np.X instead of numpy.X. 

To check the version of numpy use the command

In [3]:
print (np.__version__)

1.21.2


### Arrays

The central feature of Numpy is the *array* object class. Arrays are similar to lists in Python, execept that every element of an array must be of the same type. Items in the collection can be accessed using a zero-based index.

In [4]:
# Syntax 
np.array

<function numpy.array>

In [7]:
x = np.array([1,2,4,5])   # Python assigns the data type creates one- dimensional array

print(x)


[1 2 4 5]


In [8]:
# what is its type? 
print(" type:", type(x))

 type: <class 'numpy.ndarray'>


In [9]:
# What is stored. Type of the item can be checked with the dtype property
print("type of variable:",x.dtype)



type of variable: int64


In [10]:
      
# how many elements
print("size:", np.size(x))

size: 4


In [11]:
x = np.array([1.0,2,4.0,5.0])   # Python assigns the data type
print(x.dtype)
print(x)

float64
[1. 2. 4. 5.]


In [17]:
# you can use to force the type
x = np.array([1, 2, 4, 5], float)
print(x)
print("type of x:", x.dtype)

y = np.array(["1", "2", "4", "5", "abc"])
print(y)
print("type of y:", y.dtype)


[1. 2. 4. 5.]
type of x: float64
['1' '2' '4' '5' 'abc']
type of y: <U3


Here, the function array takes two arguments: the list to be converted into the array and the type of each member of the list.

#### ndarray.shape

This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [18]:
# Shape of the array have one dimension
print(x.shape)
print(y.shape)

(4,)
(5,)


As there are four elements it prints 4. another way of finding the dimension is use len() function. 


In [21]:
len(x)

4

In [20]:
len(y)

5

In [23]:
# repeat a sequence 10 times

print(np.array([2]*10))


[2 2 2 2 2 2 2 2 2 2]


### How to create a multidimensional array. 

Two dimensional array are great fro represening matrices which are often used in data science.


In [25]:
a = np.array([[10, 20, 30], [40, 50, 60]], float)
print(a)
print('\n')
print('Shape of a', a.shape)

b = np.array([[10, 20], [40, 50], [100, 101]], float)
print(b)
print('\n')
print('Shape of b', b.shape)

[[10. 20. 30.]
 [40. 50. 60.]]


Shape of a (2, 3)
[[ 10.  20.]
 [ 40.  50.]
 [100. 101.]]


Shape of b (3, 2)


## Reshaping arrays

In [30]:
# This resizes the ndarray
a = np.arange(0,9)
m = a.reshape(3,3)
print(m)
print('\n')
# back to original 
reshaped = m.reshape(9)
print(reshaped)

# The .reshape method is not the only means of reoragnizing data. Another
# means is the .ravle() method that will f;latten a matrix into one dimension

raveled = m.ravel()
print("m:", m)
print("raveled:", raveled)

raveled[0] = 100
print("raveled is ", raveled)
print("m is ", m)


# .flatten is like a ravel, but a copy of the data not a view into the source
m2 = np.arange(0,9).reshape(3,3)
flattened = m2.flatten()
flattened[0]= 1000
print(flattened)
print(m2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[0 1 2 3 4 5 6 7 8]
raveled: [0 1 2 3 4 5 6 7 8]
m: [[0 1 2]
 [3 4 5]
 [6 7 8]]
raveled is  [100   1   2   3   4   5   6   7   8]
m is  [[100   1   2]
 [  3   4   5]
 [  6   7   8]]
[1000    1    2    3    4    5    6    7    8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### numpy.empty
It creates an uninitialized array of specified shape and dtype.

In [38]:
x = np.empty([3,3], dtype = int)
print(x)

[[2305843009213693952 2305843009213693952                   5]
 [                  0 8171552219854798848 7221293519647039845]
 [7364560998028947501 3270567942746353716 3775764935388770357]]


#### Note: 
The elements in an array show random values as they are not initialized


#### numpy.zeros 
Returns a new array of specified size, filled with zeros.

In [39]:
x = np.zeros(10, dtype  = int)
print(x)

[0 0 0 0 0 0 0 0 0 0]


#### numpy.ones 
Returns a new array of specified size and type, filled with ones.


In [40]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [41]:
x = np.ones([3,3], dtype = int) 
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


we will discuss how to create an array from existing data

#### numpy.asarray

In [46]:
# convert list to ndarray
a = [1,2,3,4]
print(type(a))
x = np.asarray(a)
print(x)
print(type(x))

b = ["xxx","yyy","zzz"]
print(type(b))
y = np.asarray(b)
print(y)
print(y.shape)
print(type(y))


<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
<class 'list'>
['xxx' 'yyy' 'zzz']
(3,)
<class 'numpy.ndarray'>


In [44]:
# dtype is set
a = [1,2,3,4]
print(type(a))
x = np.asarray(a, dtype = float)
print(x)
print(type(x))

<class 'list'>
[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [45]:
# ndarray from tuple 
a = (1,2,3) 
print(type(a))
x = np.asarray(a) 
print(x)
print(x.shape)
print(type(x))

<class 'tuple'>
[1 2 3]
(3,)
<class 'numpy.ndarray'>


In [22]:
# ndarray from list of tuples 
a = [(1,2,3),(4,5,6)] 
x = np.asarray(a) 
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


#### Array from Numerical ranges

we will see how tocerate an array from numerical ranges


#### numpy. arange

This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −

numpy.arange(start, stop, step, dtype)

In [24]:
x = np.arange(10)
print(x)

y = np.arange(5, 10, 2)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[5 7 9]


Here default start is zero and step size is one. 

In [24]:
# start and stop parameters set 
import numpy as np 
x = np.arange(1,10,2) 
print(x)

[1 3 5 7 9]


#### numpy.linspace
This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

numpy.linspace(start, stop, num, endpoint, retstep, dtype)

1. start - The starting value of the sequence

2.  stop - The end value of the sequence, included in the sequence if endpoint set to true

3.	num - The number of evenly spaced samples to be generated. Default is 50

4.	endpoint- True by default, hence the stop value is included in the sequence. If false, it is not included

5.	retstep - If true, returns samples and step between the consecutive numbers

6.	dtype - Data type of output ndarray


In [25]:
x = np.linspace(10,20,5) 
print(x)

[10.  12.5 15.  17.5 20. ]


In [51]:
# endpoint set to false 
import numpy as np 
x = np.linspace(10,20, 5, endpoint = False, retstep=True) 
print(x)

(array([10., 12., 14., 16., 18.]), 2.0)


In [2]:
# find retstep value 
import numpy as np 

x = np.linspace(1,3,5, retstep = True) 
print(x) 
# retstep here is 0.5

(array([1. , 1.5, 2. , 2.5, 3. ]), 0.5)


#### Indexing and slicing
Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects.

Items in ndarray object follows zero-based index.

Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [12]:
a = np.arange(20)
print(a)
print(type(a))
s = slice(2, 10, 2)
print(a[s])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
[2 4 6 8]


In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In the above example, an ndarray object is prepared by arange() function. Then a slice object is defined with start, stop, and step values 2, 10, and 2 respectively. When this slice object is passed to the ndarray, a part of it starting with index 2 up to 10 with a step of 2 is sliced.

The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object.

In [13]:
x = a[2:10:2]
print(x)

[2 4 6 8]


If only one parameter is put, a single item corresponding to the index 
will be returned. If a : is inserted in front of it, all items from that index onwards will be extracted. If two parameters (with : between them) is used, items between the two indexes (not including the stop index) with default step one are sliced.

In [15]:
a = np.arange(10) 
print(a)
b = a[3] 
print (b)

[0 1 2 3 4 5 6 7 8 9]
3


In [35]:
# slice items starting from index 
a = np.arange(10) 
print(a[3:])

[3 4 5 6 7 8 9]


In [16]:
# slice items between indexes 
a = np.arange(10) 
print(a[5:7])

[5 6]


The above description applies to multi-dimensional ndarray too

In [19]:
x = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(x)
print(x.shape)
print(type(x))

# slice items starting from index
print('Now we will slice the array from the index a[1:] \n')
print(x[1:])
print()
print(x[2:])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
<class 'numpy.ndarray'>
Now we will slice the array from the index a[1:] 

[[40 50 60]
 [70 80 90]]

[[70 80 90]]


Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.

In [39]:
x = np.array([[10,20,30],[40,50,60],[70,80,90]]) 

print ('Our array is:') 
print(x)
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (x[...,1]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (x[1,...]) 
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (x[...,1:])

Our array is:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


The items in the second column are:
[20 50 80]


The items in the second row are:
[40 50 60]


The items column 1 onwards are:
[[20 30]
 [50 60]
 [80 90]]


In [33]:
x1 = np.arange(10,100,5).reshape(6,3)
np.delete
print(x1)

x2 = np.arange(10,55,5)
# np.delete

print("\n")
print(x2)
x2 = x2.reshape(3,3)
print(x2)

[[10 15 20]
 [25 30 35]
 [40 45 50]
 [55 60 65]
 [70 75 80]
 [85 90 95]]


[10 15 20 25 30 35 40 45 50]
[[10 15 20]
 [25 30 35]
 [40 45 50]]


In [35]:
x1[:,1]

array([15, 30, 45, 60, 75, 90])

In [37]:
x1[[0,2,4,5],[1,2,1,2]]

array([15, 50, 75, 95])

In [42]:
x1[1:3,1:]

array([[30, 35],
       [45, 50]])

In [40]:
# x =  [[10 20 30]
#       [40 50 60]
#       [70 80 90]]
# this returns array of items in the second column 
print ('The items in the second column are:')  
print (x[:,1]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (x[1,:]) 
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (x[:,1:])

The items in the second column are:
[20 50 80]


The items in the second row are:
[40 50 60]


The items column 1 onwards are:
[[20 30]
 [50 60]
 [80 90]]


#### Boolean Array Indexing
In this example, items greatre than 50 are returned


In [45]:
# Now we will print the items greater than 50 
'''
 x =  [[10 20 30]
       [40 50 60]
       [70 80 90]]
'''
print ('The items greater than 50 are:' )
x1g50=(x[x > 50])
print(type(x1g50))
print(x)
print(x1g50)
print(len(x1g50))

The items greater than 50 are:
<class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[60 70 80 90]
4


In [46]:
# In this example, NaN elements are omitted using ~
x = np.array([np.nan, 10, 20, np.nan, 30, 40, 50])
print(x)
print(x[~np.isnan(x)])


[nan 10. 20. nan 30. 40. 50.]
[10. 20. 30. 40. 50.]


#### Broadcasting

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [46]:
x1 = np.array([10,20,30,40]) 
x2 = np.array([10,20,30,40]) 
x = x1 * x2 
print(x)

[ 100  400  900 1600]


If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.


In [47]:
x1 = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
x2 = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (x1) 
print ('\n')  
   
print ('Second array:') 
print (x2) 
print ('\n')  
   
print ('First Array + Second Array') 
print(x1+x2)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


#### Iterating over array 

NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

Let us create a 3X4 array using arange() function and iterate over it using nditer.

In [48]:
x = np.arange(0,60,5)
x = x.reshape(3,4)

print ('Original array is:')
print (x)
print ('\n')

print ('Modified array is:')
for i in np.nditer(x):
   print (i),

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [49]:
for i in np.nditer(x, order = "F"):
   print (i),

0
20
40
5
25
45
10
30
50
15
35
55


In [53]:
np.nditer(x)

In [52]:
type(np.nditer(x))


numpy.nditer

#### Array Manipulation
Several routines are available in numpy package for manipultion of elements in
ndarray object. we will discuss few of them 

numpy.reshape

In [54]:
x = np.arange(12)
print ('The original array:')
print (x)
print ('\n')

x1 = x.reshape(4,3)
print ('The modified array:')
print (x1)

The original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


The modified array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### numpy.ndarray.flat
This function returns a 1-D iterator over the array.

In [57]:
x = np.arange(8, 20).reshape(3,4) 
print ('The original array:') 
print (x) 
print ('\n') 

print ('After applying the flat function:') 
# returns element corresponding to index in flattened array 
print (x.flat[6])
print (x.flat[0])
print (x.flat[-3])

The original array:
[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


After applying the flat function:
14
8
17


#### numpy.ndarray.flatten
This function returns a copy of an array collapsed into one dimension.

In [59]:
x = np.arange(8, 20).reshape(3, 4)

print('The original array is:')
print(x)
print('\n')
# default is column-major

print('The flattened array is:')
print(x.flatten())
print('\n')

print('The flattened array in F-style ordering:')
y = x.flatten(order='F')
print(type(y))
print(y)


The original array is:
[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


The flattened array is:
[ 8  9 10 11 12 13 14 15 16 17 18 19]


The flattened array in F-style ordering:
<class 'numpy.ndarray'>
[ 8 12 16  9 13 17 10 14 18 11 15 19]


#### Transpose Operations

numpy.transpose


In [54]:
x = np.arange(12).reshape(3,4)

print ('The original array is:') 
print (x)  
print ('\n') 

print ('The transposed array is:') 
print (np.transpose(x))

print('Alternatively, this can also be perfromed with the .T property:')
print(x.T)

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Alternatively, this can also be perfromed with the .T property:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### Joining Arrays

numpy.concatenate


Concatenation refers to joining. This function is used to join two or more arrays of the same shape along a specified axis.

In [60]:
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print('dim of a: ', a.shape)
print ('\n')  
b = (np.array([[5,6],[7,8]])) 
print ('Second array:') 
print (b) 
print('dim of b: ', b.shape)
print ('\n')  
# both the arrays are of same dimensions

print ('Joining the two arrays along axis 0:') 
print (np.concatenate((a,b))) 
print ('\n')  

print ('Joining the two arrays along axis 1:') 
print (np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]
dim of a:  (2, 2)


Second array:
[[5 6]
 [7 8]]
dim of b:  (2, 2)


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [61]:
# numpy.hstack

import numpy as np 
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  

print ('Horizontal stacking:') 
c = np.hstack((a,b)) 
print (c) 
print ('\n')
print(c.shape)

print ('Vertical stacking:') 
d = np.vstack((a,b)) 
print (d) 
print ('\n')
print(d.shape)



First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]


(2, 4)
Vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


(4, 2)


In [57]:
# numpy.vstack

import numpy as np 
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  

print ('Horizontal stacking:') 
c = np.vstack((a,b)) 
print (c) 
print ('\n')
print(c.shape)

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


(4, 2)


numpy.split

This function divides the array into subarrays along a specified axis.



In [65]:
a = np.arange(4, 13) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Split the array in 3 equal-sized subarrays:' )
b = np.split(a,3) 
print (b) 
print ('\n')
print(type(b))
print(b[0])

First array:
[ 4  5  6  7  8  9 10 11 12]


Split the array in 3 equal-sized subarrays:
[array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


<class 'list'>
[4 5 6]


In [68]:
print ('Split the array at positions indicated in 1-D array:' )
b = np.split(a,[3, 7])
print (b) 

Split the array at positions indicated in 1-D array:
[array([4, 5, 6]), array([ 7,  8,  9, 10]), array([11, 12])]


numpy.hsplit

The numpy.hsplit is a special case of split() function where axis is 1 indicating a horizontal split regardless of the dimension of the input array.

In [72]:
a = np.arange(16).reshape(4, 4)

print('First array:')
print(a)
print('\n')

print('Horizontal splitting:')
b = np.hsplit(a, 2)
print(b)
print(b[0])
print(b[0][0])
print(b[0][0][1])
print('\n')


First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[0 1]
1




numpy.vsplit

The numpy.vsplit is a special case of split() function where axis is 1 indicating a horizontal split regardless of the dimension of the input array.

In [61]:
a = np.arange(4, 20).reshape(4, 4)

print('First array:')
print(a)
print('\n')

print('Vertical splitting:')
b = np.vsplit(a, 2)
print(b)
print('\n')


First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]




numpy.resize

This function returns a new array with the specified size. If the new size is greater than the original, the repeated copies of entries in the original are contained.

In [77]:
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:') 
print (a) 
print ('\n')

print ('The shape of first array:' )
print (a.shape) 
print ('\n')  
b = np.resize(a, (3,2)) 

print ('Second array:') 
print (b) 
print ('\n')  

print ('The shape of second array:') 
print (b.shape) 
print ('\n')

# Observe that first row of a is repeated in b since size is bigger 

print ('Resize the second array:' )
b = np.resize(a,(3,10)) 
print (b)

First array:
[[1 2 3]
 [4 5 6]]


The shape of first array:
(2, 3)


Second array:
[[1 2]
 [3 4]
 [5 6]]


The shape of second array:
(3, 2)


Resize the second array:
[[1 2 3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4 5 6]]


numpy.insert 

This function inserts values in the input array along the given axis and before the given index. If the type of values is converted to be inserted, it is different from the input array. 

Also, if the axis is not mentioned, the input array is flattened.

In [4]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])

print('First array:')
print(a)
print('\n')

print('Axis parameter not passed. The input array is flattened before insertion.')
print(np.insert(a, 3, [11, 12]))
print('\n')
print('Axis parameter passed. The values array is broadcast to match input array.')

print('Broadcast along axis 0:')
print(np.insert(a, 1, [11, 15], axis=0))
print('\n')

print('Broadcast along axis 1:')
print(np.insert(a, 1, [11, 13, 15], axis=1))
print(np.insert(a, 1, 11, axis=1))


First array:
[[1 2]
 [3 4]
 [5 6]]


Axis parameter not passed. The input array is flattened before insertion.
[ 1  2  3 11 12  4  5  6]


Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 1  2]
 [11 15]
 [ 3  4]
 [ 5  6]]


Broadcast along axis 1:
[[ 1 11  2]
 [ 3 13  4]
 [ 5 15  6]]
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


numpy.delete

This function returns a new array with the specified subarray deleted from the input array. It behaves almost same way as numpy.insert


In [23]:
a = np.arange(2, 14).reshape(3,4) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Array flattened before delete operation as axis not used:' )
print (np.delete(a,5)) 
print ('\n')  

print ('Column 2 deleted:')  
print (np.delete(a,1,axis = 1)) 
print ('\n')  

print ('row 2 deleted:')  
print (np.delete(a,1,axis = 0)) 
print ('\n') 

print ('A slice containing alternate values from array deleted:') 
a = np.array([1,2,3,4,5,6,7,8,9,10]) 
print(np.s_[::2])
print (np.delete(a, np.s_[::2]))

First array:
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


Array flattened before delete operation as axis not used:
[ 2  3  4  5  6  8  9 10 11 12 13]


Column 2 deleted:
[[ 2  4  5]
 [ 6  8  9]
 [10 12 13]]


row 2 deleted:
[[ 2  3  4  5]
 [10 11 12 13]]


A slice containing alternate values from array deleted:
slice(None, None, 2)
[ 2  4  6  8 10]


Lists can also be created from arrays:

In [25]:
a = np.array([1, 2, 3], float)
print(type(a))
a1=a.tolist()
type(a1)

<class 'numpy.ndarray'>


list

One can fill an array with a single value

In [9]:
a = np.array([1, 2, 3], float)
print(a)
a.fill(0)
print(a)

[1. 2. 3.]
[0. 0. 0.]


In [87]:
# create a 2x2 array filled with 10.0
x1 = np.full((2,2), 10.0)
print(x1)

[[10. 10.]
 [10. 10.]]


In [12]:
# create a 2x2 matrix with the diagonal 1s and the others 0s
x = np.eye(2,2)
print(x)

x1= np.identity(2)
print(x1)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


The *eye* function returns matrix with ones along the kth diagonal:

In [13]:
 np.eye(3, k=1, dtype=float)  # upper diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.eye(3, k=-1, dtype=float)  # lower diagonal

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

## Array Operations/Mathematics
When standard mathematical operations are used with arrays, they are applied on an element- by-element basis. This means that the arrays should be the same size during addition, subtraction, etc.:

In [16]:
a = np.array([1,2,3], float)
b = np.array([5,3,6], float)
print(a + b)
print('\n')
np.add(a,b)

[6. 5. 9.]




array([6., 5., 9.])

In [17]:
print(a-b)
print(np.subtract(a, b))


[-4. -1. -3.]
[-4. -1. -3.]


In [18]:
print(a*b)

print(np.multiply(a,b))

[ 5.  6. 18.]
[ 5.  6. 18.]


In [74]:
print(a/b)

np.divide(a,b)

[0.2 1.  0.5]


array([0.2, 1. , 0.5])

For two-dimensional arrays, multiplication remains elementwise and does not correspond to matrix multiplication. There are special functions for matrix math that we will cover later.

In [19]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
a * b


array([[ 2.,  0.],
       [ 3., 12.]])

In [20]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
print(a)
print(b)
print(a + b)

print(np.add(a,b))   ## we can use add funtion from numpy

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[-1.  3.]
[[0. 5.]
 [2. 7.]
 [4. 9.]]
[[0. 5.]
 [2. 7.]
 [4. 9.]]


In addition to the standard operators, NumPy offers a large library of common mathematical functions that can be applied elementwise to arrays. Among these are the functions: *abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh,and arctanh*. The functions *floor, ceil, and rint* give the lower, upper, or nearest (rounded) integer:

In [96]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [97]:
np.floor(np.sqrt(a))

array([[1., 1.],
       [1., 2.],
       [2., 2.]])

Also included in the NumPy module are two important mathematical constants: pi and exponent


In [98]:
np.pi

3.141592653589793

In [80]:
np.e

2.718281828459045

In [102]:
print(a)
print(np.e**4)
print(np.e**6)
print(np.exp(a))

[[1. 2.]
 [3. 4.]
 [5. 6.]]
54.59815003314423
403.428793492735
[[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]


### Basic Array operations

Many functions exist for extracting whole-array properties. The items in an array can be summed or multiplied:

In [82]:
a = np.array([2, 4, 3], float)
print("sum of elements:", a.sum())

print(" another way:")
print("product of elements:", np.sum(a))


sum of elements: 9.0
 another way:
product of elements: 9.0


In [83]:
a = np.array([2, 4, 3], float)
print("product of elements:", a.prod())

print(" another way:")
print("product of elements:", np.prod(a))

product of elements: 24.0
 another way:
product of elements: 24.0


In [84]:
a = np.array([2, 4, 3], float)
print("product of elements:", a.prod())

print(" another way:")
print("product of elements:", np.prod(a))

product of elements: 24.0
 another way:
product of elements: 24.0


In [85]:
print(a.mean())

print(" another way:")
print("mean:", np.mean(a))

3.0
 another way:
mean: 3.0


In [86]:
print(a.min())

print(" another way:")
print("mean:", np.min(a))  

2.0
 another way:
mean: 2.0


For multidimensional arrays, each of the functions thus far described can take an optional argument axis that will perform an operation along only the specified axis, placing the results in a return array:

In [21]:
a = np.array([[0, 2], [3, -1], [3, 5]])
print(a)

[[ 0  2]
 [ 3 -1]
 [ 3  5]]


In [105]:
print(a.min(axis = 0))   # 0 for column

print(" another way:")
print("min:", np.min(a, axis = 0))

[ 0 -1]
 another way:
min: [ 0 -1]


In [106]:
print(a)

print(a.min(axis = 1))   # 1 for row

print(" another way:")
print("min:", np.min(a, axis = 1))

[[ 0  2]
 [ 3 -1]
 [ 3  5]]
[ 0 -1  3]
 another way:
min: [ 0 -1  3]


#### numpy.amin() and numpy.amax()

These functions return the minimum and the maximum from the elements in the given array along the specified axis.


In [107]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('array is:') 
print (a)  
print ('\n')  

print ('Applying amin() function:') 
print (np.amin(a,1)) 
print ('\n')  

print ('Applying amin() function again:') 
print (np.amin(a,0)) 
print ('\n')  

print ('Applying amax() function:') 
print (np.amax(a)) 
print ('\n')  

print ('Applying amax() function again:') 
print (np.amax(a, axis = 0))

print ('Applying amax() function again: axis = 1 for row') 
print (np.amax(a, axis = 1))

array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function:
[3 3 2]


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() function again:
[8 7 9]
Applying amax() function again: axis = 1 for row
[7 8 9]


In [91]:
#### numpy.percentil()


a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print ('Given array is:') 
print (a) 
print ('\n')  

print ('Applying percentile() function:') 
print (np.percentile(a,50)) 
print ('\n')  

print ('Applying percentile() function along axis 1:') 
print (np.percentile(a,50, axis = 1) )
print ('\n')  

print ('Applying percentile() function along axis 0:') 
print (np.percentile(a,50, axis = 0))

Given array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying percentile() function:
50.0


Applying percentile() function along axis 1:
[40. 20. 60.]


Applying percentile() function along axis 0:
[50. 40. 60.]


In [22]:
arr = [20, 2, 7, 1, 34]
print(sum(arr))
print("arr : ", arr)
print("50th percentile of arr : ",
       np.percentile(arr, 50))
print("25th percentile of arr : ",
       np.percentile(arr, 25))
print("75th percentile of arr : ",
       np.percentile(arr, 75))

64
arr :  [20, 2, 7, 1, 34]
50th percentile of arr :  7.0
25th percentile of arr :  2.0
75th percentile of arr :  20.0


In [92]:
print(a.mean(axis = 1))   # 1 for row

print(" another way:")
print("mean:", np.mean(a, axis = 1))

[46.66666667 36.66666667 66.66666667]
 another way:
mean: [46.66666667 36.66666667 66.66666667]


#### numpy.power()

This function treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array

In [93]:
a = np.array([10,100,1000]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying power function:') 
print (np.power(a,2)) 
print ('\n')  

print ('Second array:') 
b = (np.array([1,2,3])) 
print (b) 
print ('\n')  

print ('Applying power function again:') 
print (np.power(a,b))

Our array is:
[  10  100 1000]


Applying power function:
[    100   10000 1000000]


Second array:
[1 2 3]


Applying power function again:
[        10      10000 1000000000]


In addition to the mean, var, and std functions, Numpy supplies several other methods for returning statistical features of arrays. The correlation coefficient for multiple variables observed at multiple instances can be found for arrays of the form [[x1, x2, ...], [y1, y2, ...], [z1, z2, ...], ...] where x, y, z are different observables and the numbers indicate the observation times:


In [94]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]])
print(a)
c = np.corrcoef(a)
print(c)

[[1 2 1 3]
 [5 3 1 8]]
[[1.         0.72870505]
 [0.72870505 1.        ]]


In [95]:
a = np.array([6, 2, 5, -1, 0])
sorted(a)
a.sort()
a

array([-1,  0,  2,  5,  6])


For two dimensional arrays, the diagonal can be extracted:

In [96]:
a = np.array([[1, 2], [3, 4]], float)
#a.diagonal()

print(np.diagonal(a))

[1. 4.]


## Dot Product on Matrices and Inner Product on Vectors:

In [97]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [98]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


It is also possible to generate inner, outer, and cross products of matrices and vectors. For vectors, note that the inner product is equivalent to the dot product:

In [99]:
x1 = np.array([1, 4, 0])
y1 = np.array([2, 2, 1])

In [100]:
np.outer(x1,y1)

array([[2, 2, 1],
       [8, 8, 4],
       [0, 0, 0]])

In [101]:
np.inner(x1,y1)

10

In [102]:
np.cross(x1,y1)

array([ 4, -1, -6])

NumPy also comes with a number of built-in routines for linear algebra calculations. These can be found in the sub-module linalg. Among these are routines for dealing with matrices and their inverses. The determinant of a matrix can be found:

In [103]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]])

np.linalg.det(a)

-48.00000000000003

In [104]:
# inverse of a matrix
b = np.linalg.inv(a)
print(b)

[[ 0.22916667  0.04166667 -0.29166667]
 [ 0.04166667 -0.08333333  0.58333333]
 [-0.3125      0.125       0.125     ]]


In [105]:
(np.dot(a,b))

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [106]:
# numpy determinant
a = np.array([[1,2], [3,4]]) 
print (np.linalg.det(a))

-2.0000000000000004


In [107]:
# numpy.linalg.inv()

x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x) 
print (y) 
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


One can find the eigenvalues and eigenvectors of a matrix

In [108]:
vals, vecs = np.linalg.eig(a)
print("eigen value:", "\n")
print(vals)
print("eigen vectrs:", "\n")
print(vecs)


eigen value: 

[-0.37228132  5.37228132]
eigen vectrs: 

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Singular value decomposition (analogous to diagonalization of a nonsquare matrix) can also be performed:

In [109]:
a = np.array([[1, 3, 4], [5, 2, 3]], float)
U, s, Vh = np.linalg.svd(a)
print(U, "\n")
print(s, "\n")
print(Vh, "\n")


[[-0.6113829  -0.79133492]
 [-0.79133492  0.6113829 ]] 

[7.46791327 2.86884495] 

[[-0.61169129 -0.45753324 -0.64536587]
 [ 0.78971838 -0.40129005 -0.46401635]
 [-0.046676   -0.79349205  0.60678804]] 



## Set Operations:


In [110]:
x1 = np.array(['John','Stacy','Ron'])
x2 = np.array(['Don','Mat','Ron'])
print(x1, x2)

['John' 'Stacy' 'Ron'] ['Don' 'Mat' 'Ron']


In [111]:
print( np.intersect1d(x1,x2))

['Ron']


In [112]:
print( np.union1d(x1,x2))

['Don' 'John' 'Mat' 'Ron' 'Stacy']


In [113]:
print( np.setdiff1d(x1,x2)) # elements in x1 and not in x2

['John' 'Stacy']


In [114]:
print( np.in1d(x1,x2))   # elements in x1 in x2

[False False  True]


 It is possible to test whether or not values  are NAN ("not a number") or finite

In [115]:
a = np.array([1, np.NaN, np.Inf])
a

array([ 1., nan, inf])

In [116]:
np.isnan(a)

array([False,  True, False])

In [117]:
np.isfinite(a)

array([ True, False, False])

There are various logical operations also.

In [118]:
a = np.array([[6, 4], [5, 9]])

In [119]:
a>=5

array([[ True, False],
       [ True,  True]])

In [120]:
a[a>=5]  # Returs the elements greater or equal to 5


# another way
indx = (a>=5)

a[indx]


array([6, 5, 9])

In [121]:
# Logical and operation

a[np.logical_and(a>5, a<9)]

array([6])

For multidimensional arrays, we have to send multiple one-dimensional integer arrays to the selection bracket, one for each axis. Then, each of these selection arrays is traversed in sequence: the first element taken has a first axis index taken from the first member of the first selection array, a second index from the first member of the second selection array, and so on.

In [122]:
a = np.array([[1, 4], [9, 16]], float)
print(a)
indx_row = np.array([0, 0, 1, 1, 0,1], int)
indx_col = np.array([0, 1, 1, 1, 1,0], int)
a[indx_row, indx_col]

[[ 1.  4.]
 [ 9. 16.]]


array([ 1.,  4., 16., 16.,  4.,  9.])

However, arrays that do not match in the number of dimensions will be 
broadcasted by Python to perform mathematical operations. 
This often means that the smaller array will be repeated as necessary 
to perform the operation indicated. Consider the following:

Errors are thrown if arrays do not match in size:

In [1]:
a = np.array([1,2,3], float)
b = np.array([4,5], float)
b+a

NameError: name 'np' is not defined

### Random Numbers
An important part of any simulation is the ability to draw random numbers. For this purpose, we use NumPy's built-in pseudorandom number generator routines in the sub-module random. The numbers are pseudo random in the sense that they are generated deterministically from a seed number, but are distributed in what has statistical similarities to random fashion. NumPy uses a particular algorithm called the Mersenne Twister to generate pseudorandom numbers.
The random number seed can be set:

In [125]:
np.random.seed(1234)

The seed is an integer value. Any program that starts with the same seed will generate exactly the same sequence of random numbers each time it is run. This can be useful for debugging purposes, but one does not need to specify the seed and in fact, when we perform multiple runs of the same simulation to be averaged together, we want each such trial to have a different sequence of random numbers. If this command is not run, NumPy automatically selects a random seed (based on the time) that is different every time a program is run.
An array of random numbers in the half-open interval [0.0, 1.0) can be generated:

In [126]:
# Create an array of random numbers between 0 and 1

x1 = np.random.random(3)
print(x1, "\n")
x3= np.random.random((2,2))
print(x3)

[0.19151945 0.62210877 0.43772774] 

[[0.78535858 0.77997581]
 [0.27259261 0.27646426]]


In [127]:
# Create an array of random integers between 1 and 20
x3= np.random.randint(1,20, 11)
print(x3)

[12 13 17  6 17 10 16 19 17 13  6]


In [128]:
# To draw from a continuous normal distribution with mean = 1 and std = 10 
# and 20 points
x3= np.random.normal(1, 10, 100000)
print(np.mean(x3))
print(np.std(x3))

# To draw from a continuous normal distribution with mean = 0 and std = 1 
# and 20 points
x4= np.random.normal(size = 20)

1.0095838063538471
10.006003175120192


In [129]:
# Function for rounding
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print ('Original array:') 
print (a) 
print ('\n')  

print ('After rounding:') 
print (np.around(a)) 
print (np.around(a, decimals = 1)) 

Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]


In [130]:
# numpy.floor()


a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print ('The given array:') 
print (a) 
print ('\n')  

print ('The modified array:') 
print (np.floor(a))

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-2.  1. -1.  0. 10.]


In [131]:
# numpy.ceil()


a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print ('The given array:') 
print (a) 
print ('\n')  

print ('The modified array:') 
print (np.ceil(a))

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-1.  2. -0.  1. 10.]


#### I/O with numpy

The ndarray objects can be saved to and loaded from the disk files. The IO functions available are −

load() and save() functions handle /numPy binary files (with npy extension)

loadtxt() and savetxt() functions handle normal text files

This .npy file stores data, shape, dtype and other information required to reconstruct the ndarray in a disk file such that the array is correctly retrieved even if the file is on another machine with different architecture.

numpy.save() stores teh input array file with .npy extension

To reconstruct array from outfile.npy, use load() function.

In [132]:
x = np.array([10,20,30,40,50]) 
np.save('out_x',x)

In [133]:
data = np.load('out_x.npy') 
print(data)

[10 20 30 40 50]


In [134]:
x = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',x) 
y = np.loadtxt('out.txt') 
print (x)

[1 2 3 4 5]


In [135]:
# Reading a .csv file

#It's possible to use NumPy to directly read csv or other files into arrays. 
#We can do this using the 
#numpy.genfromtxt function.
#NumPy will automatically pick a data type for the elements in an array 
#based on their format.


df = np.genfromtxt("coursera_logistic_data.csv", delimiter=",", skip_header=1)
df
type(df)
df.shape

OSError: coursera_logistic_data.csv not found.

NumPy contains many other built-in functions that we have not covered here. In particular, there are routines for discrete Fourier transforms, more complex linear algebra operations, size / shape / type testing of arrays, splitting and joining arrays, histograms, creating arrays of numbers spaced in various ways, creating and evaluating functions on grid arrays, treating arrays with special (NaN, Inf) values, set operations, creating various kinds of special matrices, and evaluating special mathematical functions (e.g., Bessel functions). You are encouraged to consult the NumPy documentation at http://docs.scipy.org/doc/ for more details.

In [53]:
import math
# def isPrime(data):
#     isPrime = True
#     for i in range(2, data):
#         if data % i == 0:
#             print("not prime", data, "=", i, "*", data/i)
#             isPrime = False
#             break
#     if isPrime:
#         print(data, "is prime")

for data in range(2, 30):
    isPrime = True
    for i in range(2, data):
        if data % i == 0:
            print("not prime", data, "=", i, "*", data/i)
            isPrime = False
            break
    if isPrime:
        print(data, "is prime")


2 is prime
3 is prime
not prime 4 = 2 * 2.0
5 is prime
not prime 6 = 2 * 3.0
7 is prime
not prime 8 = 2 * 4.0
not prime 9 = 3 * 3.0
not prime 10 = 2 * 5.0
11 is prime
not prime 12 = 2 * 6.0
13 is prime
not prime 14 = 2 * 7.0
not prime 15 = 3 * 5.0
not prime 16 = 2 * 8.0
17 is prime
not prime 18 = 2 * 9.0
19 is prime
not prime 20 = 2 * 10.0
not prime 21 = 3 * 7.0
not prime 22 = 2 * 11.0
23 is prime
not prime 24 = 2 * 12.0
not prime 25 = 5 * 5.0
not prime 26 = 2 * 13.0
not prime 27 = 3 * 9.0
not prime 28 = 2 * 14.0
29 is prime
